language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
install:
  - pip install python-coveralls -r tests/requirements-tests.txt
script: pytest
after_success:
  - coveralls --cov=calculator